export interface ICar {
    id: string,
    make: string,
    model: string,
    year: number,
    color: string,
    body: string,
    engine: string,
    seats: number,
    mileage: number,
    mpg: number,
    description: string,
    price: number,
    vin: string,
    created: Date,
    features: string[],
    images: string[],
}